### ISSUE TITLE
animation or overlay during page loads

### ISSUE THREAD

**Issue by zerosix** [MacGapProject/MacGap2#10]
since there is no page loading status in macgap1, it can be confusing to the user when a page is loading, since there is nothing to show that it is. It would be ideal to have a way to define some sort of overlay or animation that comes up when a page begins loading and disappears when loading is done.

**Comment by gobijan** [comment]
Not really. You can have a look at the current APIs and maybe you can add something via a pull request to the native to js bridge?

**Comment by loretoparisi** [comment]
@gobijan uhm that's a way... In the meanwhile I have tried

```Objective-C
- (void)webView:(WebView *)sender didFinishLoadForFrame:(WebFrame *)frame
{
    [Event triggerEvent:@"MacGap.load.complete" forWebView:sender];
    // @see https://github.com/MacGapProject/MacGap2/issues/19
    NSScrollView *wvScrollView = sender.mainFrame.frameView.documentView.enclosingScrollView;
    [wvScrollView setVerticalScrollElasticity:NSScrollElasticityNone];
    
    //[progressIndicator stopAnimation: self];
    NSLog(@"Loading ended");
}

- (void)webView:(WebView *)sender didStartProvisonalLoadForFrame:(WebFrame *)frame{
    //[progressIndicator startAnimation: self];
    NSLog(@"Loading started...");
}
```

But I don't get the `didStartProvisonalLoadForFrame` for every page, not sure why.
