### ISSUE TITLE
Help/Q - ReferenceError: Can't find variable: macgap

### ISSUE THREAD

**Issue by Luch76** [MacGapProject/MacGap2#101]
Hello,
I'm new to Mac-development and MacGap... When I run the app I'm trying, I get the below error... Can someone help with how to fix? 

ReferenceError: Can't find variable: macgap

Steps I did: 
I did: git clone https://github.com/MacGapProject/MacGap2.git
I opened Xcode project and modified index.html as such: 
  <script type="text/javascript" charset="utf-8">
      macgap.window.resize({width: 1050, height: 810});
      window.location.href = 'https://www.gmail.com';
  </script>

Note: I only replaced the <script> tag in the body, not the entire html file

And then ran the app and I get the error.

If I remove the line: macgap.window.resize({width: 1050, height: 810});

Then it does run okay.

**Comment by jeff-h** [comment]
MacGap exposes an object to the Javascript environment as `MacGap` so you'll need to camelcase your references to `macgap`.

I feel the documentation could be improved by the addition of a simple example, and/or a single simple MacGap command in the default `index.html`. If you get things up and running, a PR for either would be great :)
