### ISSUE TITLE
cant open pop-up windows on macgap2

### ISSUE THREAD

**Issue by cancian** [MacGapProject/MacGap2#36]
On macgap1 it would open normally. I use that for Facebook auth, so it pretty much got me stuck with the old version, but i'd love to work with macgap2. Beta is thrilling :)

**Comment by eliasisrael** [comment]
@desduvauchelle Did you find a method or workaround?

**Comment by desduvauchelle** [comment]
@eliasisrael  I'm not a front-end developer so this stuff is way above my head and was easier to revert back to macgap1 (ie I really appreciate what the macgap team is doing :) ).
