### ISSUE TITLE
Conflict with Popclip/iClip/TextExpander

### ISSUE THREAD

**Issue by OleksandrRakovets** [MacGapProject/MacGap2#63]
Hello!

We had built the app on MacGap2, sandboxed it and release to Mac App Store. Some users complained that after install they have Cut/Copy/Paste items disabled in the main menu and TextExpander shortcuts failed to expand. Unfortunately we cannot reproduce it ourselves.

Have you ever faced such issue? How we can prevent it?

**Comment by jeff-h** [comment]
Congrats on getting your MacGap2 app on the MAS! :)

I've not experienced the problem you mentioned (for a start I don't use TextExpander); about the only way to really sort this would be if you're able to replicate the problem (and probably then put up a sample app so we can also replicate it).

**Comment by perfaram** [comment]
BTW, what is the name of your app ? I could try to replicate the bug – would it help ?

**Comment by OleksandrRakovets** [comment]
I didn't use TextExpander either. Managed to get rid of the issue by force enabling menu items from javascript. Did not find the root cause unfortunately.
