### ISSUE TITLE
Does anybody know about a "Windows"Gap solution ?

### ISSUE THREAD

**Issue by rsaccon** [MacGapProject/MacGap2#71]
MacGap works great for me and I would like to have something similar for windows as well, which uses under the hood edgehtml.dll and comes as C++ Visual Studio project.

**Comment by Montoya** [comment]
Currently I'm using http://nwjs.io/ for Windows / Linux support. Node + Chromium packaged into the app. 

You can also build Windows 8 apps using HTML5 in Visual Studio: http://www.htmlgoodies.com/html5/javascript/lets-get-started-building-javascript-and-html5-powered-windows-8-apps.html#fbid=i3Vrdn-uBy4 but if you want to support older Windows versions, NWJS is the only solution I know of.

**Comment by rsaccon** [comment]
thanks a lot, I will look into that htmlgoodies link !
