### ISSUE TITLE
How to fix (set the minimal and/or maximal) the window size?

### ISSUE THREAD

**Issue by li-xinyang** [MacGapProject/MacGap2#74]
I found a similar issue in **MacGap1** repository at [here](https://github.com/MacGapProject/MacGap1/issues/115). The solution is to listen the `window.onresize` event in order to prevent the window size been changed by user.

After read through the **MacGap2** documentation, I did not find any event related to changing the window size. Am I missing anything?

Thanks for your viewing and time.

**Comment by jeff-h** [comment]
> I did not find any event related to changing the window size.

The `window.onresize` is just the native Javascript event, so it should work fine under MacGap 2.
