### ISSUE TITLE
is it possible to allow generic HTML5 notifications by default? 

### ISSUE THREAD

**Issue by piggyslasher** [MacGapProject/MacGap2#82]
I have basic HTML5 app that triggers notifications when certain certain patters are found in data. We work with non profit and would to like to create an app that notifies people if they are near danger (HTML5 Notifications, triggered by a push notification. There would basicaly be about 2-3 of these devices in every room where people can know if they are safe. Any chance the valid HTML5 notification API would work. Can I just throw my app in and it works?

**Comment by jeff-h** [comment]
Sorry if I'm misunderstanding your question, but RESTful doesn't push data. If you're able to get away with your client polling a RESTful endpoint (e.g. every 2 minutes or something) then you can avoid running nodejs on the server and setting up web sockets or whatever.

Regarding HTML5 notifications — part of the beauty of RESTful is that it frees you up to do anything you like on the client side. So in that sense, what you do client-side has nothing to do with RESTful. If the client is an HTML5 app then it can do absolutely any HTML5 thing it wants with the RESTful data, including notifications.

**Comment by piggyslasher** [comment]
Erm, I think you answered the wrong question here. I was referring to [native HTML notifications](http://www.audero.it/demo/web-notifications-api-demo.html). Can we just use this method to show notifications from MacGap? Rather than using the `MacGap.Notify` helper like so:

```javascript
MacGap.Notify.notify({
    type: 'sheet',
    title: 'A title',
    content: 'Some content.'
});
```
method? On the same topic, can we auto-enable notifications, rather than have the user needing to 'Allow Notifications'?

**Comment by jeff-h** [comment]
Oh man — totally wrong repository! Sorry!

I haven't used the HTML5 `Notify` stuff inside MacGap, so you'd just have to try it. However, it's not sounding too promising e.g http://stackoverflow.com/questions/14237086/how-to-handle-html5-web-notifications-with-a-cocoa-webview

Could you write an adapter function so that standard HTML5 Notification calls get sent to your adapter and then through to MacGap?

**Comment by piggyslasher** [comment]
Ideally, this would be the way I would like to go for the next project. I.e. A new one. I am probably going to look around to see if there’s anyway to inject a user script into a MacGap app. I.e. Loading from a remote domain and injecting a script in order to ‘override’ notifications. I believe our current app has tonnes of places where there needs to be a code change. I will look around if there’s a way to create a pseudo-object such as Notifications that mirrors the HTML5 notifications object and also is a wrapper for MacGap notify().

I’m wondering how apps like Slack or Glip do this. Pretty sure they don’t want to be writing two sets of notification code. Do let me know if there’s a user script workaround.

-- 
Vik Ramanujam
Sent with Airmail

On 26 January 2016 at 9:49:51 AM, jeff-h (notifications@github.com) wrote:

Oh man — totally wrong repository! Sorry!

I haven't used the HTML5 Notify stuff inside MacGap, so you'd just have to try it. However, it's not sounding too promising e.g http://stackoverflow.com/questions/14237086/how-to-handle-html5-web-notifications-with-a-cocoa-webview

Could you write an adapter function so that standard HTML5 Notification calls get sent to your adapter and then through to MacGap?

**Comment by jeff-h** [comment]
A little tricky, I agree.

If you were happy to modify your app's every current call to the HTML5 notifications (simplistically, a find-and-replace should do the trick), one solid solution would be to write a tiny wrapper function which determines what environment the app is running under (MG2 or browser) and forwards to HTML5 notifications or to MG2 as appropriate.

**Comment by loretoparisi** [comment]
Any update on this? @jeff-h I'm using HTML5 notifications like

```javascript
notificationShow = function (notif) {
        if (!Notification) {
            return;
        }
        if (Notification.permission !== "granted") {
            Notification.requestPermission();
        } else {
            var notification = new Notification(notif.title, {
                icon: notif.icon,
                body: notif.body,
            });
            notification.onclick = function () {
                window.open(notif.link);
            };
        }
    }//notifyUser
```

but I cannot see the notification pop up in `macOS`.

**Comment by loretoparisi** [comment]
**[UPDATE]**
I have added support in this PR https://github.com/MacGapProject/MacGap2/pull/89
It can be improved, but it works as it is!
Hope this help!

**Comment by jeff-h** [comment]
Brilliant, thanks!
