### ISSUE TITLE
MacGap bad behaviour in Mojave 10.14.4 beta

### ISSUE THREAD

**Issue by jmaynardgit** [MacGapProject/MacGap2#94]
With The only change being an upgrade to Mojave 10.14.4 beta my MacGap app fails when one particular link is clicked and shows an error message:
'There is no app set to open the URL gap:/ready'
Message repeats several times per second and Mac has to be rebooted to stop...

Suggestions for fix welcome
thanks

**Comment by jeff-h** [comment]
Sorry I overlooked this issue; if it is still relevant feel free to reopen.
