### ISSUE TITLE
macOS Catalina support?

### ISSUE THREAD

**Issue by puccaso** [MacGapProject/MacGap2#95]
Hello!

a question regarding upcoming macOS changes,

Will the app/project support Catalina and the 64bit app requirement?

**Comment by jeff-h** [comment]
Hi! I'm not running the beta so can't prove it, but because you actually compile MacGap using Xcode like any other native app, I don't see why Catalina and the 64-bit requirement should be an issue.

**Comment by puccaso** [comment]
Ok awesome. I think i just needed some motivation. I'll get back to you if there are any issues. =]
