### ISSUE TITLE
How to modify the scrollbar color?

### ISSUE THREAD

**Issue by tbrodbeck** [MacGapProject/MacGap2#98]
Hi! I would like to have a dark scrolling bar in my wrapped Application. I tried to modify the css, but without any success (maybe I do not know the exact syntax though).
Is it even possible to modify the scrollbar color in MacGaps?

**Comment by jeff-h** [comment]
You should be able to style the scrollbars with CSS the same as you would in a web page. Perhaps have a look at https://css-tricks.com/custom-scrollbars-in-webkit/

**Comment by tbrodbeck** [comment]
Yeah thats what I mean by trying to modify the CSS.
More specifically, changing the `style` section does not change anything. As an example (of your link):
```
  <style type="text/css" media="screen">
    ::-webkit-scrollbar {
        width: 12px;
    }
     
    ::-webkit-scrollbar-track {
        -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
        border-radius: 10px;
    }
     
    ::-webkit-scrollbar-thumb {
        border-radius: 10px;
        -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5);
    }

  </style>
```
